services:
  db:
    image: postgres:15
    container_name: financial-db
    restart: always
    env_file:
      - ./infra/db.env
    networks:
      - private_network
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api
      dockerfile: ../infra/Dockerfile
    container_name: financial-api
    env_file:
      - ./infra/api.env
    ports:
      - "8080:8080"
    volumes:
      - /api/src:/app/src
      - /api/pom.xml:/app/pom.xml
    depends_on:
      - db
    networks:
      - private_network
      - public_network

networks:
  private_network:
    driver: bridge
  public_network:
    driver: bridge


