services:
  db:
    image: postgres:15
    container_name: financial-db
    restart: always
    env_file:
      - db.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
