spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: ${DB_URL:jdbc:tc:postgresql:15-alpine:///financial_test}  # Testcontainers Postgres
    username: ${POSTGRES_USER:test_user}
    password: ${POSTGRES_PASSWORD:test_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: create-drop    # create fresh schema per test run
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  cache:
    type: caffeine              # keep caching behavior consistent

  jackson:
    serialization:
      write-dates-as-timestamps: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

management:
  endpoints:
    web:
      exposure:
        include: health, info

  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: false

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    root: WARN
    org.springframework: WARN
    com.jmfs: DEBUG