spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:15-alpine:///testdb
    username: test
    password: test
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: create-drop    # create fresh schema per test run
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

management:
  endpoints:
    web:
      exposure:
        include: health, info

  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: false

springdoc:
  swagger-ui:
    enabled: false


logging:
  level:
    com.jmfs: DEBUG
    
api.security.token.secret: "secret"
web.url: ""